version: "3.9"
services:
  web:
    build: .
    ports:
      - 5000:8090
    environment:
      FLASK_DEBUG: True
      SHADOW_LIB_DB_HOST: db
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=shadow_lib
    ports:
      - "5432:5432"

volumes:
  postgres_data:
