"""empty message

Revision ID: 176b53459b65
Revises: a47b660843f2
Create Date: 2023-01-23 16:53:00.452089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '176b53459b65'
down_revision = 'a47b660843f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_books', 'id')
    # ### end Alembic commands ###
