"""empty message

Revision ID: 88e8d6f34142
Revises: 176b53459b65
Create Date: 2023-01-24 01:58:24.193415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e8d6f34142'
down_revision = '176b53459b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
